Test/Models/ErrorViewModel.cs
namespace Test.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Test/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Test.Core.Models;
using Test.Core.Services;
using Test.Core.Utils;

namespace Test.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ClientService _clientServicio;

        public ClientsController()
        {
            _clientServicio = new();
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _clientServicio.GetAllAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var client = await _clientServicio.GetByIdAsync(id);

            if (client == null)
                return NotFound();

            return View(client);
        }

        // GET: Clients/CreateAsync
        public IActionResult Create()
        {
            ClientModel client = new();
            FillRows(client);
            return View(client);
        }

        // POST: Clients/CreateAsync
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientModel client)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ClearRows(client);
                    await _clientServicio.CreateAsync(client);
                    return RedirectToAction(nameof(Index));
                }
                return View(client);
            }
            catch (Exception ex)
            {
                (bool show, string code, string exMessage) = ExceptionHandler.HandleException(ex);
                ModelState.AddModelError("ErrorMessage", exMessage);
                FillRows(client);
                return View(client);
            }
        }


        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var client = await _clientServicio.GetByIdAsync(id);

            if (client.Equals(null))
                return NotFound();

            FillRows(client);
            return View(client);
        }

        // POST: Clients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClientModel client)
        {
            if (id != client.Id)
                return NotFound();

            try
            {
                if (!ModelState.IsValid)
                    return View(client);

                ClearRows(client);
                var result = await _clientServicio.UpdateAsync(client);
                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                (bool show, string code, string exMessage) = ExceptionHandler.HandleException(ex);
                FillRows(client);
                ModelState.AddModelError("ErrorMessage", exMessage);
                return View(client);
            }

        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var client = await _clientServicio.GetByIdAsync((int)id);

            if (client == null)
                return NotFound();

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _clientServicio.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _clientServicio.Exists(id);
        }

        private static void ClearRows(ClientModel client)
        {
            client.Emails = client.Emails.Where(x => !(x.Id == 0 && x.EmailAddress.HaveNotValue())).ToList();
            client.Addresses = client.Addresses.Where(x => !(x.Id == 0 && x.Description.HaveNotValue())).ToList();
            client.Phones = client.Phones.Where(x => !(x.Id == 0 && x.Number.HaveNotValue())).ToList();
        }

        private static void FillRows(ClientModel client)
        {
            for (var i = 1; client.Emails.Count < 2; i++)
                client.Emails.Add(new EmailModel { EmailAddress = string.Empty });
            for (var i = 1; client.Addresses.Count < 2; i++)
                client.Addresses.Add(new AddressModel { Description = string.Empty });
            for (var i = 1; client.Phones.Count < 2; i++)
                client.Phones.Add(new PhoneModel { Number = string.Empty });
        }

    }
}

Test/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Test.Models;

namespace Test.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Test/Views/Clients/Create.cshtml
@model Test.Core.Models.ClientModel

@{
    ViewData["Title"] = "CreateAsync";
}
<div class="row">
    <h4>Create</h4>
    <form asp-action="Create">
        <div class="card">            
            <div class="card-header bg-dark text-light">
                <h5>Clientes</h5>
            </div>
            <div class="card-body row col-md-12">
                <div class="form-group col-md-3">
                    <label asp-for="@Model.DNI" class="control-label"></label>
                    <input asp-for="@Model.DNI" class="form-control" />
                    <span asp-validation-for="@Model.DNI" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.LastName" class="control-label"></label>
                    <input asp-for="@Model.LastName" class="form-control" />
                    <span asp-validation-for="@Model.LastName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.BirthDate" class="control-label"></label>
                    <input asp-for="@Model.BirthDate" class="form-control" />
                    <span asp-validation-for="@Model.BirthDate" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="my-3"></div>
        <div class="card">
            <div class="card-header bg-dark text-light">
                    <h5>Contact</h5>
            </div>
            <div class="card-body row col-md-12">
                <div class="col-md-3">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Emails.Count; i++)
                        {
                        
                            <input type="hidden" asp-for="@Model.Emails[i].Id" />
                            <label class="control-label">Email @(i+1)</label>
                            @Html.EditorFor(x => x.Emails[i].EmailAddress, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Emails[i].EmailAddress" class="text-danger"></span>
                        }
                        <span asp-validation-for="@Model.Emails" class="text-danger"></span>                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Addresses.Count; i++)
                        {                        
                            <input type="hidden" asp-for="@Model.Addresses[i].Id" />
                            <label class="control-label">Address @(i+1)</label>
                            @Html.EditorFor(x => x.Addresses[i].Description, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Addresses[i].Description" class="text-danger"></span>                        
                        }
                        <span asp-validation-for="@Model.Addresses" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Phones.Count; i++)
                        {
                        
                            <input type="hidden" asp-for="@Model.Phones[i].Id" />
                            <label class="control-label">Phones @(i+1)</label>
                            @Html.EditorFor(x => x.Phones[i].Number, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Phones[i].Number" class="text-danger"></span>
                        
                        }
                    </div>
                    <span asp-validation-for="@Model.Phones" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="my-3"></div>
         <span asp-validation-for="@Model.ErrorMessage" class="text-danger"></span>
        <div class="my-3"></div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="my-3"></div>
        <div class="col-md-12">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Test/Views/Clients/Delete.cshtml
@model Test.Core.Models.ClientModel

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="offset-md-3 col-md-6">    
        <h4>Delete</h4>
        <h5 class="text-danger">Are you sure you want to delete this?</h5>
        <div class="card">
            <div class="card-header bg-dark text-light">
                <h5>Cliente</h5>
            </div>
            <div class="card-body row">
                <dl class="row">
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.DNI)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.DNI)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.BirthDate)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.BirthDate)
                    </dd>
                    @{int i = 1;}
                    @foreach (var email in @Model.Emails)
                    {
                        <dt class="col-sm-2">
                            Email @i
                        </dt>
                        <dd class="col-sm-10">
                            @email.EmailAddress
                        </dd> 
                        ++i;
                    }
                     @{ i = 1;}
                    @foreach (var address in @Model.Addresses)
                    {
                        <dt class="col-sm-3">
                            Address @i
                        </dt>
                        <dd class="col-sm-9">
                            @address.Description
                        </dd>
                         ++i;
                    }
                    @{ i = 1;}
                    @foreach (var phone in @Model.Phones)
                    {
                        <dt class="col-sm-3">
                            Phone @i
                        </dt>
                        <dd class="col-sm-9">
                            @phone.Number
                        </dd>
                         ++i;
                    }
                </dl>
            </div>
        </div>
    </div>
    <div class="my-3"></div>
    <div class="offset-md-3 col-md-6">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Test/Views/Clients/Details.cshtml
@model Test.Core.Models.ClientModel

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <h4>Details</h4>
    <div class="offset-md-3 col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-light">
                <h5>Cliente</h5>
            </div>
            <div class="card-body row">
                <dl class="row">
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.DNI)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.DNI)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.BirthDate)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.BirthDate)
                    </dd>
                    @{int i = 0;}
                    @foreach (var email in @Model.Emails)
                    {
                        <dt class="col-sm-2">
                            Email
                        </dt>
                        <dd class="col-sm-10">
                            @email.EmailAddress
                        </dd> 
                        ++i;
                    }
                     @{ i = 0;}
                    @foreach (var address in @Model.Addresses)
                    {
                        <dt class="col-sm-3">
                            Address
                        </dt>
                        <dd class="col-sm-9">
                            @address.Description
                        </dd>
                         ++i;
                    }
                    @{ i = 0;}
                    @foreach (var phone in @Model.Phones)
                    {
                        <dt class="col-sm-3">
                            Phone
                        </dt>
                        <dd class="col-sm-9">
                            @phone.Number
                        </dd>
                         ++i;
                    }
                </dl>
            </div>
        </div>
    </div>
    <div class="my-3"></div>
    <div class="offset-md-3 col-md-6">
        <div class="form-group">
            <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

Test/Views/Clients/Edit.cshtml
@model Test.Core.Models.ClientModel

@{
    ViewData["Title"] = "Edit";
}
<div class="row">
    <h4>Edit</h4>
    <form asp-action="Edit">
        <div class="card">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card-header bg-dark text-light">
                <h5>Cliente</h5>
            </div>
            <div class="card-body row col-md-12">
                <div class="form-group col-md-3">
                    <input type="hidden" asp-for="@Model.Id" />
                    <label asp-for="@Model.DNI" class="control-label"></label>
                    <input asp-for="@Model.DNI" class="form-control" />
                    <span asp-validation-for="@Model.DNI" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.LastName" class="control-label"></label>
                    <input asp-for="@Model.LastName" class="form-control" />
                    <span asp-validation-for="@Model.LastName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="@Model.BirthDate" class="control-label"></label>
                    <input asp-for="@Model.BirthDate" class="form-control" />
                    <span asp-validation-for="@Model.BirthDate" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="my-3"></div>
        <div class="card">
            <div class="card-header bg-dark text-light">
                <h5>Contact</h5>
            </div>
            <div class="card-body row col-md-12">
                <div class="col-md-3">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Emails.Count; i++)
                        {
                        
                            <input type="hidden" asp-for="@Model.Emails[i].Id" />
                            <label class="control-label">Email @(i+1)</label>
                            @Html.EditorFor(x => x.Emails[i].EmailAddress, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Emails[i].EmailAddress" class="text-danger"></span>
                        }
                        <span asp-validation-for="@Model.Emails" class="text-danger"></span>                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Addresses.Count; i++)
                        {                        
                            <input type="hidden" asp-for="@Model.Addresses[i].Id" />
                            <label class="control-label">Address @(i+1)</label>
                            @Html.EditorFor(x => x.Addresses[i].Description, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Addresses[i].Description" class="text-danger"></span>                        
                        }
                        <span asp-validation-for="@Model.Addresses" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group m-0 p-2">
                        @for (int i = 0; i < Model.Phones.Count; i++)
                        {
                        
                            <input type="hidden" asp-for="@Model.Phones[i].Id" />
                            <label class="control-label">Phones @(i+1)</label>
                            @Html.EditorFor(x => x.Phones[i].Number, new { htmlAttributes = new { @class="form-control" }, data_val = false } )
                            <span asp-validation-for="@Model.Phones[i].Number" class="text-danger"></span>
                        
                        }
                    </div>
                    <span asp-validation-for="@Model.Phones" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="my-3"></div>
         <span asp-validation-for="@Model.ErrorMessage" class="text-danger"></span>
        <div class="my-3"></div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="my-3"></div>
        <div class="col-md-12">            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-success" /> |
                <a  asp-action="Index">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Test/Views/Clients/Index.cshtml
@model IEnumerable<Test.Core.Models.ClientModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Clients</h1>

<p>
    <a class="btn btn-primary btn-sm mr-0" asp-action="Create">Create New</a>
</p>
<table class="table table-responsive borde">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="table-secondary">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DNI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    <a class="btn btn-success btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn btn-warning btn-sm" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Test/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="border-0 border-dark border-bottom-1 ">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info text-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Test .NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="m-1 pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-light">
        <div class="container">
            &copy; 2022 - Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>